### ISSUE TITLE
Zadania

### ISSUE THREAD

**Issue by adamsApzumi** [KarolCieslar/Zadanie-Rekrutacja#1]
Dzień dobry,
Dziękuję za podesłanie rozwiązania. W zadaniu brakuje testów oraz README z instrukcja jak uruchomić aplikację, i opisu API. Prośba o uzupełnienie powyższych elementów, dopiero wtedy przystąpię do weryfikacji.

Pozdrawiam,
Adam

**Comment by KarolCieslar** [comment]
Dziękuję za informację.
Jeśli chodzi o brak README to nie zwróciłem na to uwagi przy commitowaniu. Nie wiem dlaczego tak się stało, plik miałem przygotowany od razu po zakończeniu projektu.

Testów nie udało mi się niestety napisać. W żadnym swoim projekcie nie robiłem do tej pory testów. Jedyną wzmiankę jaką o nich miałem była na kursie w CodersLab. Przed wysłaniem zadania dałem sobie 2 dni na ich napisanie ale nie miałem kiedy do tego przysiąść. Domyślam się, że testy do tak prostego programu nie byłyby trudne aczkolwiek nie mogłem nigdzie znaleźć pasującego przykładu jaki mógłbym użyć.

Jeśli brak testów zaważy na przejściu do kolejnego etapu wówczas prosiłbym o danie mi kilku dni abym mógł znaleźć chwilę na ich napisanie. Aktualnie przygotowuję wszelkie formalności i załatwiam sprawy do własnego wesela i nie mam na nic czasu ;/

**Comment by adamsApzumi** [comment]
Rozumiem, powodzenia w przygotowywaniu wesela :)
Mamy sporo kandydatów i jednym z kryterium oceny zadania są właśnie testy. Proszę w takim razie je przygotować, zobaczymy jak wyjdą jeżeli to pierwsze podejście do tematu. Oczywiście nie musze być na jutro :) Czy termin środa w następnym tygodniu Panu wystarczy?

**Comment by KarolCieslar** [comment]
Dziękuję za zrozumienie!
W środę do wieczora wyślę zadanie.

**Comment by KarolCieslar** [comment]
@adamsApzumi Uważam zadanie za wykonane. Na tyle ile umiałem zrobiłem testy. 
Uprzejmie proszę o sprawdzenie zadania.

**Comment by adamsApzumi** [comment]
Dziękuję. Aktualnie przeglądamy również rozwiązania pozostałych kandydatów. 
Weronika poinformuje o ewentualnym dalszym etapie rekrutacji.
